### ISSUE TITLE
金币那个地方是不是已经失效了？

### ISSUE THREAD

**Issue by Chrisma-98** [QiuYueBaiJXW/UnicomGetCoin#1]
我找了半天也没找到金币的入口，而且金币那里直接未登陆了。
而且金币那个地方，出错了
【
login success!
querySigninActivity success!
daySign success!
coin: {"msg":"用户未登录","status":"0001"}
】

**Comment by QiuYueBaiJXW** [comment]
金币的那个API好像有问题，我忘了给注释掉了…

**Comment by QiuYueBaiJXW** [comment]
等我有空再看看吧

**Comment by QiuYueBaiJXW** [comment]
> 我找了半天也没找到金币的入口，而且金币那里直接未登陆了。
> 而且金币那个地方，出错了
> 【
> login success!
> querySigninActivity success!
> daySign success!
> coin: {"msg":"用户未登录","status":"0001"}
> 】

金币那个按照联通客服的说法是  “ 手厅签到活动于2020年5月6日升级，升级后参与手厅每日签到赠送的金币将会替换为积分，积分可兑换更多优质福利！您所拥有的金币仍可在签到页“金币商城”或“兑奖品，花金币”内进行兑换。”，所以金币没用啦，我稍后修改一下重新上传
