### ISSUE TITLE
GitHub actions运行出错

### ISSUE THREAD

**Issue by kerncoola** [QiuYueBaiJXW/UnicomGetCoin#2]
![image](https://user-images.githubusercontent.com/13283995/97834294-74230100-1d12-11eb-80a4-179950060bc1.png)

**Comment by QiuYueBaiJXW** [comment]
可能是网络问题，换个网络试试，如果还有问题再说

**Comment by kerncoola** [comment]
这是在GitHub服务器端运行的，与网络关系不大吧，Secrets下面cookie的值是抓包得到的值还是全部（带Cookie:）

**Comment by QiuYueBaiJXW** [comment]
那就是你cookie抓的不对

> 这是在GitHub服务器端运行的，与网络关系不大吧，Secrets下面cookie的值是抓包得到的值还是全部（带Cookie:）

那就是你cookie填错了，仔细看教程，只要requesttime后面的cookie

**Comment by kerncoola** [comment]
![image](https://user-images.githubusercontent.com/13283995/97847958-5ca44200-1d2b-11eb-8af6-0cfa3d9f6cf9.png)
![image](https://user-images.githubusercontent.com/13283995/97847975-64fc7d00-1d2b-11eb-90dd-3903044cf01e.png)
是第一个吧

**Comment by kerncoola** [comment]
Cookie: c_sfbm=234g_00; city=051|510; logHostIP=null; route=99d4d4bd8589bc2de2ab74。。。
2020-11-02 13:38:51&simCount=1&version=iphone_c@7.0600&mobile=hS1CHuQCviDZhXoH%2BlrIi5Xtp%2。。。
两个都有。

**Comment by QiuYueBaiJXW** [comment]
> Cookie: c_sfbm=234g_00; city=051|510; logHostIP=null; route=99d4d4bd8589bc2de2ab74。。。
> 2020-11-02 13:38:51&simCount=1&version=iphone_c@7.0600&mobile=hS1CHuQCviDZhXoH%2BlrIi5Xtp%2。。。
> 两个都有。

查看请求体文本
![B0BDCFAE-0F3C-43B9-8C42-DC93A58192B8](https://user-images.githubusercontent.com/40496034/97853472-1e128580-1d33-11eb-8787-47c3bdb9a31f.jpeg)

**Comment by kerncoola** [comment]
嗯，这步没错，老哥加个微信吧，感觉都对了就是不行，就不信这个邪了，vx：kerncool

**Comment by kerncoola** [comment]
解决了，感谢老哥。
