### ISSUE TITLE
#抓包方法及内容

### ISSUE THREAD

**Issue by ye1314** [QiuYueBaiJXW/UnicomGetCoin#3]
将reqtime后面的内容按要求填入py文件
填哪里，py文件里没看到可以填入的地方

**Comment by ye1314** [comment]
还是说reqtime的内容就是 secret里的COOKIE的值

**Comment by QiuYueBaiJXW** [comment]
> 还是说reqtime的内容就是 secret里的COOKIE的值

reqtime后面的内容填到secret里
