### ISSUE TITLE
实现账号密码登陆

### ISSUE THREAD

**Issue by cyd** [QiuYueBaiJXW/UnicomGetCoin#5]
2个问题，cookie过期时间以及账号密码登陆问题。
后者实现难度较大，且能解决前者问题。

**Comment by MisterGlasses** [comment]
cookie失效太频繁了

**Comment by QiuYueBaiJXW** [comment]
这个cookie只要联通不改加密方法就不会失效，放心用

**Comment by MisterGlasses** [comment]
> 这个cookie只要联通不改加密方法就不会失效，放心用

`https://github.com/chavyleung/scripts/tree/master/10010 `
请问跟这个脚本所用的cookie是一个吗？上述脚本是进手厅签到页抓cookie，cookie经常失效。

**Comment by QiuYueBaiJXW** [comment]
> > 这个cookie只要联通不改加密方法就不会失效，放心用
> 
> `https://github.com/chavyleung/scripts/tree/master/10010 `
> 请问跟这个脚本所用的cookie是一个吗？上述脚本是进手厅签到页抓cookie，cookie经常失效。

不一样，我这个抓的是登陆链接，你抓到的内容仔细看里面有加密过的手机号和密码，其实按理来说不算是cookie，只要联通不改这个加密公钥，这玩意就可以一直用

**Comment by MisterGlasses** [comment]
> > > 这个cookie只要联通不改加密方法就不会失效，放心用
> > 
> > 
> > `https://github.com/chavyleung/scripts/tree/master/10010 `
> > 请问跟这个脚本所用的cookie是一个吗？上述脚本是进手厅签到页抓cookie，cookie经常失效。
> 
> 不一样，我这个抓的是登陆链接，你抓到的内容仔细看里面有加密过的手机号和密码，其实按理来说不算是cookie，只要联通不改这个加密公钥，这玩意就可以一直用

那挺好 可以多账号吗

**Comment by QiuYueBaiJXW** [comment]
> > > > 这个cookie只要联通不改加密方法就不会失效，放心用
> > > 
> > > 
> > > `https://github.com/chavyleung/scripts/tree/master/10010 `
> > > 请问跟这个脚本所用的cookie是一个吗？上述脚本是进手厅签到页抓cookie，cookie经常失效。
> > 
> > 
> > 不一样，我这个抓的是登陆链接，你抓到的内容仔细看里面有加密过的手机号和密码，其实按理来说不算是cookie，只要联通不改这个加密公钥，这玩意就可以一直用
> 
> 那挺好 可以多账号吗

多账号加个循环就好了，你可以自己改，我懒得搞了

**Comment by MisterGlasses** [comment]
> > > > > 这个cookie只要联通不改加密方法就不会失效，放心用
> > > > 
> > > > 
> > > > `https://github.com/chavyleung/scripts/tree/master/10010 `
> > > > 请问跟这个脚本所用的cookie是一个吗？上述脚本是进手厅签到页抓cookie，cookie经常失效。
> > > 
> > > 
> > > 不一样，我这个抓的是登陆链接，你抓到的内容仔细看里面有加密过的手机号和密码，其实按理来说不算是cookie，只要联通不改这个加密公钥，这玩意就可以一直用
> > 
> > 
> > 那挺好 可以多账号吗
> 
> 多账号加个循环就好了，你可以自己改，我懒得搞了

😂那我用两个号fork吧

**Comment by QiuYueBaiJXW** [comment]
> > > > > > 这个cookie只要联通不改加密方法就不会失效，放心用
> > > > > 
> > > > > 
> > > > > `https://github.com/chavyleung/scripts/tree/master/10010 `
> > > > > 请问跟这个脚本所用的cookie是一个吗？上述脚本是进手厅签到页抓cookie，cookie经常失效。
> > > > 
> > > > 
> > > > 不一样，我这个抓的是登陆链接，你抓到的内容仔细看里面有加密过的手机号和密码，其实按理来说不算是cookie，只要联通不改这个加密公钥，这玩意就可以一直用
> > > 
> > > 
> > > 那挺好 可以多账号吗
> > 
> > 
> > 多账号加个循环就好了，你可以自己改，我懒得搞了
> 
> 😂那我用两个号fork吧

也是个办法🤪
